export const NavbarItems = [
  {
    label: "Shop",
    children: [
      {
        label: "by products",
        children: [
          { label: "view all", link: "/products" },
          { label: " T - Shirts", link: "" },
          { label: "Oversized T-Shirts", link: "" },
          { label: "Drop Cut T-Shirts", link: "" },
          { label: "Hoodies", link: "" },
          { label: "Sweatshirts", link: "" },
          { label: "Jackets", link: "" },
          { label: "Fullsleeve T-Shirts", link: "" },
          { label: "Basics", link: "" },
          { label: "Kids T-Shirts", link: "" },
          { label: "Sleeveless T-Shirts & Tank Tops", link: "" },
        ],
      },
      {
        label: "Accessories",
        children: [
          { label: "View All", link: "/products/accessories" },
          { label: "Stickers", link: "" },
          { label: "Mobile Covers", link: "" },
          { label: "Mugs", link: "" },
          { label: "Caps", link: "" },
          { label: "Posters", link: "" },
          { label: "Face Masks", link: "" },
          { label: "Fridge Magnets", link: "" },
          { label: "Coasters", link: "" },
          { label: "Badges", link: "" },
          { label: "Spiral Notebooks", link: "" },
          { label: "Pins", link: "" },
          { label: "Socks", link: "" },
          { label: "Mouse Pads", link: "" },
          { label: "Laptop Skins", link: "" },
          { label: "Key Chains", link: "" },
          { label: "Tote Bags", link: "" },
        ],
      },
      {
        label: "By Popular Themes",
        children: [
          { label: " All Products", link: "/products" },
          { label: "Superheroes", link: "" },
          { label: "Anime", link: "" },
          { label: "Cartoons", link: "" },
          { label: "Comics", link: "" },
          { label: "Glow In The Dark", link: "" },
          { label: "Horror", link: "" },
          { label: "Film", link: "" },
          { label: "TV", link: "" },
          { label: "Slogan", link: "" },
          { label: "Funny", link: "" },
          { label: "Music", link: "" },
          { label: "Cute", link: "" },
          { label: "Geek", link: "" },
          { label: "Animals", link: "" },
          { label: "Funky", link: "" },
          { label: "Foodie", link: "" },
          { label: "Stoner & Alcohol", link: "" },
          { label: "Pattern T-Shirts", link: "" },
          { label: "Camouflage", link: "" },
          { label: "Gym", link: "" },
          { label: "Rick And Morty", link: "" },
          { label: "Avengers T-Shirts", link: "" },
          { label: "Marvel T-Shirts", link: "" },
          { label: "Iron Man T-Shirts", link: "" },
          { label: "Gaming", link: "" },
          { label: "GIFT VOUCHERS", link: "" },
          { label: "OFFICIAL MERCHANDISE", link: "" },
          { label: "UGLY CHRISTMAS SWEATERS", link: "" },
          { label: "CLEARANCE SALE", link: "" },
          { label: "MINIONS", link: "" },
          { label: "PRE-ORDERS", link: "" },
          { label: "ARCHIVE", link: "" },
          { label: "BULK & CUSTOM ORDERS", link: "" },
        ],
      },
    ],
  },
  {
    label: "Men",
    children: [
      {
        label: "Men Apparel",
        children: [
          { label: " View All", link: "/products/men" },
          { label: "Mens Hoodies", link: "" },
          { label: "Mens Sweatshirts", link: "" },
          { label: "Mens Jackets", link: "" },
          { label: "Mens T-Shirts", link: "" },
          { label: "Mens Oversized T-Shirts", link: "" },
          { label: "Mens Drop Cut T-Shirts", link: "" },
          { label: "Mens Fullsleeve T-Shirts", link: "" },
          { label: "Mens Basics", link: "" },
          { label: "Mens Sleeveless T-Shirts & Tank Tops", link: "" },
        ],
      },
    ],
  },
  {
    label: "women",
    children: [
      {
        label: "Women Apparel",
        children: [
          { label: "View All", link: "/products/women" },
          { label: "Womens T-Shirts", link: "" },
          { label: "Womens Full Sleeve T-Shirts", link: "" },
          { label: "Womens Oversized T-Shirts", link: "" },
          { label: "Womens Printed T-Shirts", link: "" },
          { label: "Womens Hoodies", link: "" },
          { label: "Womens Basics", link: "" },
          { label: "Boyfriend T-Shirts", link: "" },
        ],
      },
    ],
  },
  {
    label: "Accessories",
    children: [
      {
        label: "accessories",
        children: [
          { label: "View All", link: "/products/accessories" },
          { label: "Stickers", link: "" },
          { label: "Mobile Covers", link: "" },
          { label: "Mugs", link: "" },
          { label: "Caps", link: "" },
          { label: "Posters", link: "" },
          { label: "Face Masks", link: "" },
          { label: "Fridge Magnets", link: "" },
          { label: "Coasters", link: "" },
          { label: "Badges", link: "" },
          { label: "Spiral Notebooks", link: "" },
          { label: "Pins", link: "" },
          { label: "Socks", link: "" },
          { label: "Mouse Pads", link: "" },
          { label: "Laptop Skins", link: "" },
          { label: "Key Chains", link: "" },
          { label: "Tote Bags", link: "" },
        ],
      },
    ],
  },
  {
    label: "Characters",
    children: [
      {
        label: "Marvel",
        children: [
          { label: " Marvel Merchandise", link: "/" },
          { label: "Avengers", link: "/" },
          { label: "Spider-Man", link: "/" },
          { label: "Iron Man", link: "/" },
          { label: "Captain America", link: "/" },
          { label: "Thor", link: "/" },
          { label: "Loki", link: "/" },
          { label: "Doctor Strange", link: "/" },
          { label: "Deadpool", link: "/" },
          { label: "Black Panther", link: "/" },
          { label: "Guardians Of The Galaxy", link: "/" },
          { label: "Across The Spider-Verse", link: "/" },
          { label: "The Hulk", link: "/" },
          { label: "The Punisher", link: "/" },
          { label: "Black Widow", link: "/" },
          { label: "Venom", link: "/" },
          { label: "WandaVision", link: "/" },
          { label: "Ant-Man", link: "/" },
          { label: "X-Men", link: "/" },
          { label: "The Falcon And The Winter Soldier", link: "/" },
          { label: "What If...?", link: "/" },
          { label: "Captain Marvel", link: "/" },
          { label: "Wolverine", link: "/" },
          { label: "Ms Marvel", link: "/" },
          { label: "Moon Knight", link: "/" },
          { label: "She-Hulk", link: "/" },
          { label: "Daredevil", link: "/" },
          { label: "Hawkeye", link: "/" },
          { label: "Ghost Rider", link: "/" },
          { label: "Shang Chi", link: "/" },
          { label: "Eternals", link: "/" },
          { label: "Werewolf By Night", link: "/" },
          { label: "Carnage", link: "/" },
          { label: "Thanos", link: "/" },
        ],
      },
      {
        label: "DC Comics",
        children: [
          { label: "DC Comics Merchandise", link: "/" },
          { label: "Blue Beetle", link: "/" },
          { label: "Justice League", link: "/" },
          { label: "Batman", link: "/" },
          { label: "The Flash", link: "/" },
          { label: "Superman", link: "/" },
          { label: "Wonder Woman", link: "/" },
          { label: "Shazam", link: "/" },
          { label: "Joker", link: "/" },
          { label: "Aquaman", link: "/" },
          { label: "Green Lantern", link: "/" },
          { label: "Harley Quinn", link: "/" },
          { label: "Black Adam", link: "/" },
          { label: "Suicide Squad", link: "/" },
        ],
      },
      {
        label: "Anime",
        children: [{ label: "Naruto", link: "/" }],
      },
      {
        label: "Movies and TV",
        children: [
          { label: "Harry Potter", link: "/" },
          { label: "Friends", link: "/" },
          { label: "Star Wars", link: "/" },
          { label: "The Mandalorian", link: "/" },
          { label: "House Of The Dragon", link: "/" },
          { label: "Game Of Thrones", link: "/" },
          { label: "The Matrix", link: "/" },
          { label: "Boba Fett", link: "/" },
          { label: "Fantastic Beasts", link: "/" },
          { label: "The Big Bang Theory", link: "/" },
          { label: "The Lion King", link: "/" },
        ],
      },
      {
        label: "Cartoons and Animation",
        children: [
          { label: "Garfield", link: "/" },
          { label: "Snoopy", link: "/" },
          { label: "Rick & Morty", link: "/" },
          { label: "Looney Tunes", link: "/" },
          { label: "Bugs Bunny", link: "/" },
          { label: "Daffy Duck", link: "/" },
          { label: "Tweety", link: "/" },
          { label: "Space Jam", link: "/" },
          { label: "Tom And Jerry", link: "/" },
          { label: "Scooby Doo", link: "/" },
          { label: "Disney", link: "/" },
          { label: "Mickey Mouse", link: "/" },
          { label: "Donald Duck", link: "/" },
          { label: "Cartoon Network", link: "/" },
          { label: "Ed, Edd And Eddy", link: "/" },
          { label: "Samurai Jack", link: "/" },
          { label: "Mojo Jojo", link: "/" },
          { label: "The Powerpuff Girls", link: "/" },
          { label: "Johnny Bravo", link: "/" },
          { label: "Courage The Cowardly Dog", link: "/" },
          { label: "Dexter's Laboratory", link: "/" },
          { label: "Ben 10", link: "/" },
          { label: "Adventure Time", link: "/" },
          { label: "Spongebob Squarepants", link: "/" },
          { label: "South Park", link: "/" },
          { label: "TMNT", link: "/" },
          { label: "Fido Dido", link: "/" },
        ],
      },
      {
        label: "Collaborations",
        children: [
          { label: "ISRO", link: "/" },
          { label: "NASA", link: "/" },
        ],
      },
    ],
  },
  {
    label: "Artists",
    children: [
      {
        label: "Comedy",
        children: [
          { label: "Trevor Noah", link: "/" },
          { label: "Samay Raina", link: "/" },
          { label: "Aakash Mehta", link: "/" },
          { label: "Akshar Pathak", link: "/" },
          { label: "Bollywood Gandu", link: "/" },
          { label: "CallMeShazzam", link: "/" },
        ],
      },
      {
        label: "Music",
        children: [
          { label: "Goo Goo Dolls", link: "/" },
          { label: "Lollapalooza", link: "/" },
          { label: "Westlife", link: "/" },
          { label: "KING", link: "/" },
          { label: "Ziro", link: "/" },
          { label: "Prateek Kuhad", link: "/" },
          { label: "Parikrama", link: "/" },
          { label: "Sabotage", link: "/" },
          { label: "Fallen Letters", link: "/" },
          { label: "The Down Troddence", link: "/" },
          { label: "Control ALT Delete", link: "/" },
          { label: "Nucleya", link: "/" },
          { label: "Aabha Hanjura", link: "/" },
          { label: "Primitiv", link: "/" },
          { label: "Skyharbor", link: "/" },
          { label: "Blackstratblues", link: "/" },
          { label: "Pangea", link: "/" },
          { label: "Goddess Gagged", link: "/" },
          { label: "Sanam", link: "/" },
          { label: "Wolves", link: "/" },
          { label: "Scribe", link: "/" },
          { label: "Pentagram", link: "/" },
          { label: "Punk On Toast", link: "/" },
          { label: "Demonstealer", link: "/" },
          { label: "Demonic Resurrection", link: "/" },
          { label: "Su Real", link: "/" },
          { label: "Bombay Bassment", link: "/" },
          { label: "R.A.I.D", link: "/" },
          { label: "Undying Inc.", link: "/" },
          { label: "Killchain", link: "/" },
          { label: "Antariksh", link: "/" },
          { label: "Vinay Kaushal", link: "/" },
          { label: "Deathknell", link: "/" },
          { label: "Project Mishram", link: "/" },
          { label: "Pinecone Records", link: "/" },
        ],
      },
      {
        label: "Webseries",
        children: [
          { label: "Shit Indians Say & The Sarcastic Indian", link: "/" },
          { label: "Bacon Tadka", link: "/" },
          { label: "Headbanger's Kitchen", link: "/" },
          { label: "The Big Forkers", link: "/" },
        ],
      },
      {
        label: "Movies",
        children: [{ label: "Bhediya", link: "/" }],
      },
      {
        label: "Other",
        children: [
          { label: "Parle-G", link: "/" },
          { label: "WazirX", link: "/" },
          { label: "ABP Network", link: "/" },
          { label: "Nomads Of India", link: "/" },
          { label: "Bingo! Achha Aaloo", link: "/" },
          { label: "Doodleodrama", link: "/" },
          { label: "Chess.Com", link: "/" },
          { label: "Vitamin Stree", link: "/" },
          { label: "Moonshine", link: "/" },
          { label: "SensibleTshirts", link: "/" },
        ],
      },
    ],
  },
];
